### ISSUE TITLE
What does this connect to?

### ISSUE THREAD

**Issue by neildufva** [PickledCode/ShowSync#5]
I have checked out the readme and went through the code but I have no idea what this is actually supposed to connect to in reference to VLC, Quicktime etc... I just want to see if it works but there is nothing to try and connect it to, any help is appreciated! Would it be possible to make this work over LAN?

**Comment by RSully** [comment]
Whoops!

So the clients run this ShowSync app. They connect to a KBProxy server (https://github.com/unixpickle/KBProxy). 

Both clients input the host and port of the server in their preferences, and choose a common tag. The tag is like a password that the server uses to match you up. At that point you can choose your local media player and open the movie. 

The role of ShowSync is to share timestamps between these players. You can see what timestamp your friend is at, and you can choose to set your player to that timestamp, or you can pause and wait for your friend to catch up and ShowSync will automatically resume playback. It also will sync pauses, so if your friend pauses to grab a snack your player will pause too. 

In practice this works best when you both have a chat open, or are on a call with each other. 

Let me know if you need any further clarification. I'll see about getting the readme updated shortly.
